### ISSUE TITLE
docker-based build failed (need to update 'time' package)

### ISSUE THREAD

**Issue by zny666** [inclavare-containers/rbi#3]
`
1777.4    Compiling time v0.3.34
1777.9 error[E0282]: type annotations needed for `Box<_>`
1777.9   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
1777.9    |
1777.9 83 |     let items = format_items
1777.9    |         ^^^^^
1777.9 ...
1777.9 86 |     Ok(items.into())
1777.9    |              ---- type must be known at this point
1777.9    |
1777.9 help: consider giving `items` an explicit type, where the placeholders `_` are specified
1777.9    |
1777.9 83 |     let items: Box<_> = format_items
1777.9    |              ++++++++
`
need to update 'time' from 0.3.34 to 0.3.36(both CDH and AA)

**Comment by 1570005763** [comment]
Using the latest commit version  in the makefile will fix this. Because the version of `time` was locked to 0.3.34 by the cargo.lock file in earlier commits.

AA has been fixed by [this commit](https://github.com/inclavare-containers/docker-attestation-agent/commit/aee6876e9214873f2a297969c6393f0610c2c57f).
CDH has been fixed by [this commit](https://github.com/inclavare-containers/docker-confidential-data-hub/commit/f6ebe0f479318b1af855f61f048e75e48d3e2619).
